openapi: 3.0.3
info:
  title: ZAP accessControl quickstartlaunch API
  description: The HTTP API for controlling and accessing ZAP.
  contact:
    name: ZAP User Group
    url: https://groups.google.com/group/zaproxy-users
    email: zaproxy-users@googlegroups.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.16.1
servers:
- url: http://zap
  description: The URL while proxying through ZAP.
- url: http://{address}:{port}
  description: The URL of a Local Proxy of ZAP.
  variables:
    address:
      description: The address ZAP is listening on.
      default: 127.0.0.1
    port:
      description: The port ZAP is bound to.
      default: '8080'
security:
- {}
- apiKeyHeader: []
- apiKeyQuery: []
tags:
- name: quickstartlaunch
paths:
  /OTHER/quickstartlaunch/other/startPage/:
    get:
      description: ''
      operationId: quickstartlaunchOtherStartPage
      tags:
      - quickstartlaunch
      responses:
        default:
          $ref: '#/components/responses/ErrorOther'
components:
  responses:
    ErrorOther:
      description: Error of OTHER endpoints.
      content:
        '*/*': {}
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: X-ZAP-API-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: apikey
      in: query
