openapi: 3.0.3
info:
  title: ZAP accessControl wappalyzer API
  description: The HTTP API for controlling and accessing ZAP.
  contact:
    name: ZAP User Group
    url: https://groups.google.com/group/zaproxy-users
    email: zaproxy-users@googlegroups.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.16.1
servers:
- url: http://zap
  description: The URL while proxying through ZAP.
- url: http://{address}:{port}
  description: The URL of a Local Proxy of ZAP.
  variables:
    address:
      description: The address ZAP is listening on.
      default: 127.0.0.1
    port:
      description: The port ZAP is bound to.
      default: '8080'
security:
- {}
- apiKeyHeader: []
- apiKeyQuery: []
tags:
- name: wappalyzer
paths:
  /JSON/wappalyzer/view/listAll/:
    get:
      description: Lists all sites and their associated applications (technologies).
      operationId: wappalyzerViewListAll
      tags:
      - wappalyzer
      responses:
        default:
          $ref: '#/components/responses/ErrorJson'
  /JSON/wappalyzer/view/listSite/:
    parameters:
    - name: site
      in: query
      required: true
      description: ''
      schema:
        type: string
    get:
      description: Lists all the applications (technologies) associated with a specific site.
      operationId: wappalyzerViewListSite
      tags:
      - wappalyzer
      responses:
        default:
          $ref: '#/components/responses/ErrorJson'
  /JSON/wappalyzer/view/listSites/:
    get:
      description: Lists all the sites recognized by the Technology Detection add-on.
      operationId: wappalyzerViewListSites
      tags:
      - wappalyzer
      responses:
        default:
          $ref: '#/components/responses/ErrorJson'
components:
  responses:
    ErrorJson:
      description: Error of JSON endpoints.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorJson'
  schemas:
    ErrorJson:
      type: object
      required:
      - code
      - message
      properties:
        code:
          type: string
        message:
          type: string
        detail:
          type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: X-ZAP-API-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: apikey
      in: query
