openapi: 3.2.0
info:
  title: ZAP Authentication API
  description: The HTTP API for controlling and accessing ZAP.
  contact:
    name: ZAP User Group
    url: https://groups.google.com/group/zaproxy-users
    email: zaproxy-users@googlegroups.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.16.1
servers:
- url: http://zap
  description: The URL while proxying through ZAP.
- url: http://{address}:{port}
  description: The URL of a Local Proxy of ZAP.
  variables:
    address:
      description: The address ZAP is listening on.
      default: 127.0.0.1
    port:
      description: The port ZAP is bound to.
      default: '8080'
security:
- {}
- apiKeyHeader: []
- apiKeyQuery: []
tags:
- name: Authentication
paths:
  /JSON/authentication/action/setAuthenticationMethod/:
    parameters:
    - name: contextId
      in: query
      required: true
      description: ''
      schema:
        type: string
    - name: authMethodName
      in: query
      required: true
      description: ''
      schema:
        type: string
    - name: authMethodConfigParams
      in: query
      description: ''
      schema:
        type: string
    get:
      description: Sets the authentication method for the context with the given ID.
      operationId: authenticationActionSetAuthenticationMethod
      tags:
      - Authentication
      responses:
        default:
          $ref: '#/components/responses/ErrorJson'
      summary: Authentication action set authentication method
      x-summary-source: derived
  /JSON/authentication/action/setLoggedInIndicator/:
    parameters:
    - name: contextId
      in: query
      required: true
      description: ''
      schema:
        type: string
    - name: loggedInIndicatorRegex
      in: query
      required: true
      description: ''
      schema:
        type: string
    get:
      description: Sets the logged in indicator for the context with the given ID.
      operationId: authenticationActionSetLoggedInIndicator
      tags:
      - Authentication
      responses:
        default:
          $ref: '#/components/responses/ErrorJson'
      summary: Authentication action set logged in indicator
      x-summary-source: derived
  /JSON/authentication/action/setLoggedOutIndicator/:
    parameters:
    - name: contextId
      in: query
      required: true
      description: ''
      schema:
        type: string
    - name: loggedOutIndicatorRegex
      in: query
      required: true
      description: ''
      schema:
        type: string
    get:
      description: Sets the logged out indicator for the context with the given ID.
      operationId: authenticationActionSetLoggedOutIndicator
      tags:
      - Authentication
      responses:
        default:
          $ref: '#/components/responses/ErrorJson'
      summary: Authentication action set logged out indicator
      x-summary-source: derived
  /JSON/authentication/view/getAuthenticationMethod/:
    parameters:
    - name: contextId
      in: query
      required: true
      description: ''
      schema:
        type: string
    get:
      description: Gets the name of the authentication method for the context with the given ID.
      operationId: authenticationViewGetAuthenticationMethod
      tags:
      - Authentication
      responses:
        default:
          $ref: '#/components/responses/ErrorJson'
      summary: Authentication view get authentication method
      x-summary-source: derived
  /JSON/authentication/view/getAuthenticationMethodConfigParams/:
    parameters:
    - name: authMethodName
      in: query
      required: true
      description: ''
      schema:
        type: string
    get:
      description: Gets the configuration parameters for the authentication method with the given name.
      operationId: authenticationViewGetAuthenticationMethodConfigParams
      tags:
      - Authentication
      responses:
        default:
          $ref: '#/components/responses/ErrorJson'
      summary: Authentication view get authentication method config params
      x-summary-source: derived
  /JSON/authentication/view/getLoggedInIndicator/:
    parameters:
    - name: contextId
      in: query
      required: true
      description: ''
      schema:
        type: string
    get:
      description: Gets the logged in indicator for the context with the given ID.
      operationId: authenticationViewGetLoggedInIndicator
      tags:
      - Authentication
      responses:
        default:
          $ref: '#/components/responses/ErrorJson'
      summary: Authentication view get logged in indicator
      x-summary-source: derived
  /JSON/authentication/view/getLoggedOutIndicator/:
    parameters:
    - name: contextId
      in: query
      required: true
      description: ''
      schema:
        type: string
    get:
      description: Gets the logged out indicator for the context with the given ID.
      operationId: authenticationViewGetLoggedOutIndicator
      tags:
      - Authentication
      responses:
        default:
          $ref: '#/components/responses/ErrorJson'
      summary: Authentication view get logged out indicator
      x-summary-source: derived
  /JSON/authentication/view/getSupportedAuthenticationMethods/:
    get:
      description: Gets the name of the authentication methods.
      operationId: authenticationViewGetSupportedAuthenticationMethods
      tags:
      - Authentication
      responses:
        default:
          $ref: '#/components/responses/ErrorJson'
      summary: Authentication view get supported authentication methods
      x-summary-source: derived
components:
  schemas:
    ErrorJson:
      type: object
      required:
      - code
      - message
      properties:
        code:
          type: string
        message:
          type: string
        detail:
          type: string
  responses:
    ErrorJson:
      description: Error of JSON endpoints.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorJson'
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: X-ZAP-API-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: apikey
      in: query
